#%RAML 0.8
---
title: Sample API
baseUri: http://localhost:8081/api/v1
version: 1.0
                         
/retrieveCustomer:
    displayName: Retrieve Customer       
    get:
      description: Retrieves a list of companies matching the email/domain criteria    
      queryParameters:
        email:
          description: (optional) an email
          type: string
          required: false
          # not required, because when profile='arizona', 
          # the admin may be interested in looking at campaigns across all agencies
        companyName:
          description: the companyName (optional)
          # could be replaced by a profileId as an integer
          type: string
          required: false          
      responses:
        200:
          description: |
            companies retrieved successfully
          body:
            application/json:
              example: !include examples/publicApi/companies-get-example.json
                                
/addCloudService1:
    displayName: Add Cloud Service to Billing System 1 (json payload)          
    post:
      description: adds a Cloud Service Entry to the Customer's Billing Master Plan
      body:
        application/json:
          schema: !include schemas/_dumb-schema.json
          example: !include examples/publicApi/service-post-example.json
      responses:
        200:
          description: |
            Request Acknowledged
          body:
            application/json:
              example: |
                {
                  "status": "ACK"
                }

/addCloudService2:
    displayName: Add Cloud Service to Billing System 2 (form-urlencoded)          
    post:
      description: adds a Cloud Service Entry to the Customer's Billing Master Plan
      body:
        application/x-www-form-urlencoded:
          formParameters:
            cloudCustomerId:
              description: the SGAS customer ID
              type: integer
            cloudServiceName:
              description: the service name to add to this customers billing
              type: string
            cloudBillingSpecifics:
              description: the customer billing specifics for this customer (override defaults)
              type: string              
      responses:
        200:
          description: |
            Request Acknowledged
          body:
            application/json:
              example: |
                {
                  "status": "ACK"
                }                