#%RAML 0.8
title: cloud 2.0 API
baseUri: http://localhost:8081/api/v0
version: v0.1
               
/invoices:
  description: Retrieve list of invoices related information for a specific account and a date range
  get:
    queryParameters:
      accountNumber:
        description: Account Number
        required: true
        type: string
      startDate:  
        description: Start Date
        required: true
        type: date
      endDate:  
        description: End Date
        required: true
        type: date
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/invoice-schema.json
            example: !include examples/invoices-get-example.json
              
  /{invoiceNumber}:
    displayName: getInvoice
    description: A specific invoice
    get:
      responses:
        200:
          description: |
            Invoice retrieved successfully
          body:
            application/json:
              schema: !include schemas/invoice-schema.json
              example: !include examples/invoiceDetail-get-example.json
              
    /invoiceDetail:
        displayName: getInvoiceDetail
        description: Retrieves the Invoice Detail (usage, adjustments, etc.)
        get:
          responses:
            200:
              body:
                application/json:
                  schema: !include schemas/invoiceDetail-schema.json
                  example: !include examples/invoiceDetail-get-example.json

    /invoicePDF:
      description: Retrieves a binary (.pdf) representation of the actual invoice.
      get:
        responses:
          200:
            body:
              binary/octet-stream: 
#              multipart/form-data:                             
      
/product:
    description: Details regarding product
    /templatePrices:
      description: Computes the customer specific discounted price for an Offering in combination with all availble OS choices. The prices includes any applicable OS licensing costs (some based on attributes of the Offering). Some templates prices varies based on number of CPUs and RAM.  (OS licensing per core)
      get:
        queryParameters:
          accountNumber:
            description: Account Number
            required: true
            type: string
          offeringID:
            description: offering ID
            required: true
            type: string
          templateID:
            description: List of tempalte ID optional
            required: false
            type: string
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    {
                      "accountNumber": "AcctNo123",
                      "computeofferingID": "offeringID123",
                      "templatePriceTypes": [
                        {
                          "templateID": "templateID123",
                          "unitPrice": 25.0
                        },
                        {
                          "templateID": "templateID1234",
                          "unitPrice": 1050.0
                        }
                      ]
                    }
                  }
    /offeringPrices:
      description: Computes the customer specific discounted price for all available Offerings.
      get:
        queryParameters:
          accountNumber:
            description: Account Number
            required: true
            type: string
          offeringID:
            description: offering ID
            required: false
            type: string
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    {
                      "accountNumber": "AcctNo123",
                      "offeringPrice": [
                        {
                          "offeringID": "offeringID123",
                          "unitPrice": 250.0
                        },
                        {
                          "offeringID": "offeringID1234",
                          "unitPrice": 150.0
                        }
                      ]
                    }
                  }        
    
/customers:
  description: Retrieve list of Customers
  get:
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/customer-schema.json
            example: !include examples/customers-get-example.json
  /{customerId}:
    description: Retrieve a specific Customer
    # Note: use a helper key rather than a Pkey
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/customer-get-example.json         
            
    /customerAssociatedAccounts:
      description: Retrieve list of Customer Associated Accounts for a given customer Id
      get:
        responses:
          200:
            body:
              application/json:
                example: !include examples/customerAssociatedAccounts-get-example.json
      /{customerAssociatedAccountId}:
        description: Retrieve a specific Customer Associated Account
        get:
          responses:
           200:
            body:
              application/json:
                example: !include examples/customerAssociatedAccount-get-example.json                
    /customerBillingAccounts:
      description: Retrieve list of Customer Billing Accounts for a given customer Id
      get:
        responses:
          200:
            body:
              application/json:
                example: !include examples/customerBillingAccounts-get-example.json
      /{customerBillingAccountId}:
        description: Retrieve a specific Customer Billing Account
        get:
          responses:
           200:
            body:
              application/json:
                example: !include examples/customerAssociatedAccount-get-example.json                
        
/contacts:
    displayName: Contacts
    description: Retrieves a list of contacts          
    get:         
      responses:
        200:
          description: |
            Contacts retrieved successfully
          body:
            application/json:
              example: !include examples/contacts-get-example.json       
    post:
      description: New Contact
      body:
        application/json:
          example: !include examples/contact-post-example.json
      responses:
        200:
          description: |
            Request Acknowledged
          body:
            application/json:
              example: |
                {
                  "status": "ACK"
                }
                                    
    /{contactId}:
      displayName: getContact by Id
      description: A specific contact, a member of the contacts collection
      get:
        queryParameters:
          agencyId:
            description: the agency where the contact belongs
            type: integer
            required: true
        responses:
          200:
            description: |
              Contact retrieved successfully by Id
            body:
              application/json:
                example: !include examples/contact-get-example.json
                
    /{contactEmail}:
      displayName: getContact by Email
      description: A specific contact, a member of the contacts collection
      get:
        queryParameters:
          agencyId:
            description: the agency where the contact belongs
            type: integer
            required: true
        responses:
          200:
            description: |
              Contact retrieved successfully by Email
            body:
              application/json:
                example: !include examples/contact-get-example.json
                                
/address:
  /{addressId}:
    description: Retrieve a specific Address
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/customer-get-example.json
                   
/addressType:
  /{addressTypeId}:
    description: Retrieve a specific Address Type
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/addressType-get-example.json   
    

/AddressRelationship:
  /{addressRelationshipId}:
    description: Retrieve a specific Address Relationship
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/addressRelationship-get-example.json
               
/customerContact:
  /{addressId}:
    description: Retrieve a specific Customer Contact
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/customerContact-get-example.json
                   
/customerContactType:
  /{typeId}:
    description: Retrieve a specific Customer Contact Type
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/customerContactType-get-example.json   
    

/customerContactRelationship:
  /{relationshipId}:
    description: Retrieve a specific Customer Contact Relationship
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/customerContactRelationship-get-example.json
                             
/sgasContact:
  /{addressId}:
    description: Retrieve a specific SGAS Contact
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/sgasContact-get-example.json
                   
/sgasContactType:
  /{typeId}:
    description: Retrieve a specific SGAS Contact Type
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/sgasContactType-get-example.json   
    

/sgasContactRelationship:
  /{relationshipId}:
    description: Retrieve a specific SGAS Contact Relationship
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/sgasContactRelationship-get-example.json

/sgasContactGroup:
  /{groupId}:
    description: Retrieve a specific SGAS Contact Group
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/sgasContactGroup-get-example.json
                  
/orders:
  description: Retrieve list of Orders
  get:
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/customer-schema.json
            example: !include examples/orders-get-example.json
  /{orderId}:
    description: Retrieve a specific Order
    get:
      responses:
       200:
        body:
          application/json:
            example: !include examples/order-get-example.json
                   
    /orderLineItems:
      description: Retrieve list of Line Items for a specific Order
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schemas/customer-schema.json
                example: !include examples/orderLineItems-get-example.json
                   
      /{lineItemId}:
        description: Retrieve a specific Line Item for a given Order
        get:
          responses:
           200:
            body:
              application/json:
                example: !include examples/orderLineItem-get-example.json  
    

    /orderType:
      /{id}:
        description: Retrieve a specific Order Type for a specific order
        get:
          responses:
           200:
            body:
              application/json:
                example: !include examples/orderType-get-example.json

    /orderStatus:
      /{id}:
        description: Retrieve a specific Order Status
        get:
          responses:
           200:
            body:
              application/json:
                example: !include examples/orderStatus-get-example.json                                     
                                                                                    
#####################################                
# other entities to define as an API
#####################################
# Order + OrderLineItem, OrderType, OrderStatus

# CustomerType
# CustomerRelationship
# CustomerStatus
# Opportunity
# SizeInIndustry
# Industry
# Invoice + InvoiceLineItem, InvoiceType, InvoiceRelationship
# Usage + usageType, usageDetails
# Contract + 11 related tables
# Product + 9 related tables
 